apiVersion : apps/v1
kind: Deployment
metadata:
  name: coffeeshopcoffeeshop 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coffeeshopcoffeeshop
  template:
    metadata:
      labels:
        app: coffeeshopcoffeeshop 
    spec:
      containers:
        - name: coffeeshopcoffeeshop 
          image: circletestregistry.azurecr.io/coffeeshopcoffeeshop
          ports:
          - containerPort: 8080